// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package tubul

import (
	"time"

	"github.com/google/uuid"
)

type TubulEvent struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	EventDate time.Time `json:"event_date"`
}
