load("@aspect_rules_js//js:defs.bzl", "js_binary")

js_binary(
    # A unique name for this target.
    name = "hello_world",
    # The main script which is evaluated by node.js
    entry_point = "hello_world.js",
)
